apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-pods
  namespace: k8-executor
subjects:
- kind: User
  name: 196790176036-compute@developer.gserviceaccount.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-list
  apiGroup: rbac.authorization.k8s.io